---
- hosts: web
  vars:
    dockerport: 8888
    contport: 8080
  become: true
  tasks:
    - name: Update apt repo
      apt:  update_cache=yes name=docker.io state=present
    - name: Clone Git repo
      git:
        repo: https://github.com/pbeniwal/helloedureka.git
        dest: /home/edureka/helloedureka/
        force: yes
    - name: Build
      shell:
        cmd: mvn package
        chdir: /home/edureka/helloedureka/
    - name: Create Image
      shell:
        cmd: docker build -t mytomcat .
        chdir: /home/edureka/helloedureka/
    - name: Remove Docker Container
      shell:
        cmd: docker rm --force mytomcat || echo
    - name: Start Docker Container
      shell:
        cmd: docker run -d --name=mytomcat -p {{ dockerport }}:{{ contport }} mytomcat

